Feature: Run testcases of playwright

  Background: background

  Scenario: Login into Instagram
    Given Login to Instagram userId = 'userId' and password = 'password' playwright


  Scenario Outline: chatting.....
    Given Login to Instagram playwright
    Then Send message '<message>' to user '<userId>' on instagram playwright

    Examples:
      | testCaseId | message         | userId     |
      | 1234567    | Hii Googles.... | Zoozubieee |

  Scenario Outline: Login into Linkedin
    Given Login to Linkedin username='<username>' & password='<passcode>'
    Examples:
      | username                      | passcode |
      | ravikrishnabattala5@gmail.com | #####    |


  Scenario: Apply for Jobs
    Given Apply recommended jobs


  Scenario Outline: Login to Naukri
    Given Login to Naukri userId = '<username>' and password = '<passcode>'

    Examples:
      | username                      | passcode |
      | ravikrishnabattala5@gmail.com | #####    |


  Scenario: Apply Jobs
    Given Apply naukri jobs

  Scenario: Share Interest
    Given Share Interest to Job


  Scenario Outline: Login Apps
    Given OTP from Flipkart '<phoneNumber>'
    And OTP from Myntra '<phoneNumber>'
    And OTP from Ajio '<phoneNumber>'
    And OTP from Amazon '<phoneNumber>'
    And OTP from Meesho '<phoneNumber>'
    And OTP from Snapdeal '<phoneNumber>'
    And OTP from Nykaa '<phoneNumber>'
    And OTP from TataCLiQ '<phoneNumber>'
    And OTP from Pepperfry '<phoneNumber>'
    And OTP from FirstCry '<phoneNumber>'
    And OTP from Lenskart '<phoneNumber>'
    And OTP from PolicyBazar '<phoneNumber>'
    And OTP from ShopClues '<phoneNumber>'
    And OTP from Croma '<phoneNumber>'
    And OTP from VijaySales '<phoneNumber>'
    And OTP from DMartReady '<phoneNumber>'
    And OTP from BigBasket '<phoneNumber>'
    And OTP from Blinkit '<phoneNumber>'
    And OTP from Zepto '<phoneNumber>'
    And OTP from JioMart '<phoneNumber>'
    And OTP from NaturesBasket '<phoneNumber>'
    And OTP from eBay '<phoneNumber>'
    And OTP from Temu '<phoneNumber>'
    And OTP from Shein '<phoneNumber>'
    And OTP from Westside '<phoneNumber>'
    And OTP from Pantaloons '<phoneNumber>'
    And OTP from ShoppersStop '<phoneNumber>'
    And OTP from Lifestyle '<phoneNumber>'
    And OTP from MaxFashion '<phoneNumber>'
    And OTP from Bewakoof '<phoneNumber>'
    And OTP from SouledStore '<phoneNumber>'
    And OTP from Clovia '<phoneNumber>'
    And OTP from Mamaearth '<phoneNumber>'
    And OTP from Purplle '<phoneNumber>'
    And OTP from SugarCosmetics '<phoneNumber>'
    And OTP from Boat '<phoneNumber>'
    And OTP from Apple '<phoneNumber>'
    And OTP from Oppo '<phoneNumber>'
    And OTP from Puma '<phoneNumber>'
    And OTP from Reebok '<phoneNumber>'
    And OTP from Decathlon '<phoneNumber>'
    And OTP from Urbanic '<phoneNumber>'
    And OTP from IKEA '<phoneNumber>'
    And OTP from UrbanLadder '<phoneNumber>'
    And OTP from Wakefit '<phoneNumber>'
    And OTP from Zomato '<phoneNumber>'
    And OTP from Uber '<phoneNumber>'
    And OTP from Ola '<phoneNumber>'
    And OTP from Airbnb '<phoneNumber>'
    And OTP from OYO '<phoneNumber>'
    And OTP from MakeMyTrip '<phoneNumber>'
    And OTP from Goibibo '<phoneNumber>'
    And OTP from Yatra '<phoneNumber>'
    And OTP from leartrip '<phoneNumber>'
    And OTP from BookMyShow '<phoneNumber>'
    And OTP from RedBus '<phoneNumber>'
    And OTP from Dominos '<phoneNumber>'
    And OTP from McDonalds '<phoneNumber>'
    And OTP from UrbanCompany '<phoneNumber>'
    And OTP from NoBroker '<phoneNumber>'
    And OTP from 99acres '<phoneNumber>'
    And OTP from OLX '<phoneNumber>'
    And OTP from Quikr '<phoneNumber>'
    And OTP from Telegram '<phoneNumber>'
    And OTP from Twitter '<phoneNumber>'
    And OTP from Reddit '<phoneNumber>'
    And OTP from Canva '<phoneNumber>'
    And OTP from Spotify '<phoneNumber>'
    And OTP from Netflix '<phoneNumber>'
    And OTP from Hotstar '<phoneNumber>'
    And OTP from SonyLIV '<phoneNumber>'
    And OTP from Zee5 '<phoneNumber>'
    And OTP from Zoom '<phoneNumber>'
    And OTP from AngelOne '<phoneNumber>'
    And OTP from CoinSwitch '<phoneNumber>'
    And OTP from Niyo '<phoneNumber>'
    And OTP from IndMoney '<phoneNumber>'
    And OTP from Smallcase '<phoneNumber>'
    And OTP from Freo '<phoneNumber>'
    And OTP from MobiKwik '<phoneNumber>'
    And OTP from LazyPay '<phoneNumber>'
    And OTP from KreditBee '<phoneNumber>'
    And OTP from MoneyTap '<phoneNumber>'
    And OTP from EarlySalary '<phoneNumber>'
    And OTP from Swiggy '<phoneNumber>'
    And OTP from EatSure '<phoneNumber>'
    And OTP from Country Delight '<phoneNumber>'
    And OTP from Licious '<phoneNumber>'
    And OTP from FreshToHome '<phoneNumber>'
    And OTP from AbhiBus '<phoneNumber>'
    And OTP from Cleartrip '<phoneNumber>'
    And OTP from EaseMyTrip '<phoneNumber>'
    And OTP from ixigo '<phoneNumber>'
    And OTP from RailYatri '<phoneNumber>'
    And OTP from IndiGo '<phoneNumber>'
    And OTP from SpiceJet '<phoneNumber>'
    And OTP from AirAsia '<phoneNumber>'
    And OTP from Treebo '<phoneNumber>'
    And OTP from FabHotels '<phoneNumber>'
    And OTP from StayVista '<phoneNumber>'
    And OTP from PharmEasy '<phoneNumber>'
    And OTP from Netmeds '<phoneNumber>'
    And OTP from Tata1mg '<phoneNumber>'
    And OTP from Apollo247 '<phoneNumber>'
    And OTP from Practo '<phoneNumber>'
    And OTP from HealthifyMe '<phoneNumber>'
    And OTP from CultFit '<phoneNumber>'
    And OTP from MFine '<phoneNumber>'
    And OTP from Portea '<phoneNumber>'
    And OTP from Bajaj Health '<phoneNumber>'
    And OTP from Byju '<phoneNumber>'
    And OTP from Unacademy '<phoneNumber>'
    And OTP from Vedantu '<phoneNumber>'
    And OTP from upGrad '<phoneNumber>'
    And OTP from Testbook '<phoneNumber>'
    And OTP from PW '<phoneNumber>'
    And OTP from Doubtnut '<phoneNumber>'
    And OTP from Meritnation '<phoneNumber>'
    And OTP from TopperLearning '<phoneNumber>'
    And OTP from Embibe '<phoneNumber>'
    And OTP from Simplilearn '<phoneNumber>'
    And OTP from GreatLearning '<phoneNumber>'
    And OTP from Sharechat '<phoneNumber>'
    And OTP from Moj '<phoneNumber>'
    And OTP from Josh '<phoneNumber>'
    And OTP from Koo '<phoneNumber>'
    And OTP from Truecaller '<phoneNumber>'
    And OTP from Discord '<phoneNumber>'
    And OTP from JioCinema '<phoneNumber>'
    And OTP from MXPlayer '<phoneNumber>'
    And OTP from AltBalaji '<phoneNumber>'
    And OTP from Voot '<phoneNumber>'
    And OTP from Aha '<phoneNumber>'
    And OTP from SunNXT '<phoneNumber>'
    And OTP from Hungama '<phoneNumber>'
    And OTP from Gaana '<phoneNumber>'
    And OTP from JioSaavn '<phoneNumber>'
    And OTP from Wynk '<phoneNumber>'
    And OTP from Airtel Xstream '<phoneNumber>'
    And OTP from Naukri '<phoneNumber>'
    And OTP from Apna '<phoneNumber>'
    And OTP from Internshala '<phoneNumber>'
    And OTP from WorkIndia '<phoneNumber>'
    And OTP from Shine '<phoneNumber>'
    And OTP from Hirist '<phoneNumber>'
    And OTP from Instahyre '<phoneNumber>'
    And OTP from Cutshort '<phoneNumber>'
    And OTP from iimjobs '<phoneNumber>'
    And OTP from Foundit '<phoneNumber>'
    And OTP from MagicBricks '<phoneNumber>'
    And OTP from Housing '<phoneNumber>'
    And OTP from Sulekha '<phoneNumber>'
    And OTP from JustDial '<phoneNumber>'
    And OTP from UrbanClap '<phoneNumber>'
    And OTP from Housejoy '<phoneNumber>'
    And OTP from Dream11 '<phoneNumber>'
    And OTP from MPL '<phoneNumber>'
    And OTP from Winzo '<phoneNumber>'
    And OTP from MyTeam11 '<phoneNumber>'
    And OTP from RummyCircle '<phoneNumber>'
    And OTP from Adda52 '<phoneNumber>'
    And OTP from Jio '<phoneNumber>'
    And OTP from Airtel '<phoneNumber>'
    And OTP from VodafoneIdea '<phoneNumber>'
    And OTP from TataPlay '<phoneNumber>'
    And OTP from DishTV '<phoneNumber>'
    And OTP from d2h '<phoneNumber>'
    And OTP from Delhivery '<phoneNumber>'
    And OTP from Shiprocket '<phoneNumber>'
    And OTP from Shadowfax '<phoneNumber>'
    And OTP from Porter '<phoneNumber>'
    And OTP from Lalamove '<phoneNumber>'

    And OTP from Meatigo '<phoneNumber>'
    And OTP from BB Daily '<phoneNumber>'
    And OTP from Supr Daily '<phoneNumber>'
    And OTP from Ninjacart '<phoneNumber>'
    And OTP from Zappfresh '<phoneNumber>'
    And OTP from Milkbasket '<phoneNumber>'
    And OTP from Bounce '<phoneNumber>'
    And OTP from Yulu '<phoneNumber>'
    And OTP from Vogo '<phoneNumber>'
    And OTP from Shaw Academy '<phoneNumber>'
    And OTP from Medlife '<phoneNumber>'
    And OTP from DocPrime '<phoneNumber>'
    And OTP from Tata Health '<phoneNumber>'
    And OTP from Chingari '<phoneNumber>'
    And OTP from Roposo '<phoneNumber>'
    And OTP from MX TakaTak '<phoneNumber>'
    And OTP from Mitron '<phoneNumber>'
    And OTP from Clubhouse '<phoneNumber>'
    And OTP from Doorstep '<phoneNumber>'
    And OTP from Zupee '<phoneNumber>'
    And OTP from Hago '<phoneNumber>'
    And OTP from Loco '<phoneNumber>'
    And OTP from BSNL '<phoneNumber>'
    And OTP from BESCOM '<phoneNumber>'
    And OTP from PayNearby '<phoneNumber>'
    And OTP from Spice Money '<phoneNumber>'
    And OTP from Borzo '<phoneNumber>'
    And OTP from Wefast '<phoneNumber>'

    @GenerateOTPs
    Examples:
      | phoneNumber |
      | ****        |

  Scenario: 123
    And OTP from Ajio '8309930363'